sudo: required

dist: trusty

language: c++  # to use system python

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq -y python-opencv python-virtualenv
  - virtualenv venv
  - cp $(python -c 'import cv2; print(cv2.__file__)') venv/lib/python2.7/site-packages
  - . venv/bin/activate
  - pip install -U numpy  # for copied cv2
  - pip install .

script:
  - python tests/test.py
